"""
WARNING: v3 registers are UNTESTED

This file was generated by mapping the provided CSV's "V3 Description" values
to existing v1/v2 entity names. DO NOT assume these register addresses are
correct for your v3 device without manual verification.

Important:
- The registers listed here may be incorrect or duplicated.
- Some CSV descriptions could not be matched automatically; those addresses
    are listed under the `# UNMATCHED_CSV_ENTRIES` comment at the end of this
    file.
- Verify each register on an actual v3 device before enabling in production.

If you have test results or corrected addresses, please update this file or
provide a corrected CSV and re-run the generator.
"""

# SENSOR_DEFINITIONS
SENSOR_DEFINITIONS = [
    {
            "count": 2,
            "data_type": "int32",
            "device_class": "power",
            "enabled_by_default": True,
            "key": "battery_power",
            "name": "Battery Power",
            "precision": 1,
            "register": 30001,
            "scale": 1,
            "scan_interval": "high",
            "state_class": "measurement",
            "unit": "W",
        },
    {
            "data_type": "int16",
            "device_class": "temperature",
            "enabled_by_default": False,
            "key": "internal_mos1_temperature",
            "name": "Internal MOS1 Temperature",
            "precision": 2,
            "register": 30002,
            "scale": 0.1,
            "scan_interval": "medium",
            "state_class": "measurement",
            "unit": "°C",
        },
    {
            "data_type": "int16",
            "device_class": "temperature",
            "enabled_by_default": False,
            "key": "internal_mos2_temperature",
            "name": "Internal MOS2 Temperature",
            "precision": 2,
            "register": 30003,
            "scale": 0.1,
            "scan_interval": "medium",
            "state_class": "measurement",
            "unit": "°C",
        },
    {
            "data_type": "uint16",
            "device_class": "voltage",
            "enabled_by_default": True,
            "key": "ac_voltage",
            "name": "AC Voltage",
            "precision": 1,
            "register": 30004,
            "scale": 0.1,
            "scan_interval": "medium",
            "state_class": "measurement",
            "unit": "V",
        },
    {
            "data_type": "uint16",
            "device_class": "voltage",
            "enabled_by_default": True,
            "key": "battery_voltage",
            "name": "Battery Voltage",
            "precision": 1,
            "register": 30100,
            "scale": 0.01,
            "scan_interval": "medium",
            "state_class": "measurement",
            "unit": "V",
        },
    {
            "category": "diagnostic",
            "data_type": "uint16",
            "device_class": "diagnostic",
            "enabled_by_default": False,
            "icon": "mdi:wifi",
            "key": "wifi_signal_strength",
            "name": "WiFi Signal Strength",
            "precision": 0,
            "register": 30303,
            "scale": -1,
            "scan_interval": "high",
            "unit": "dBm",
        },
    {
            "count": 6,
            "data_type": "char",
            "enabled_by_default": True,
            "key": "mac_address",
            "name": "MAC Address",
            "precision": 0,
            "register": 30304,
            "scan_interval": "very_low",
            "unit": None,
        },
    {
            "count": 2,
            "data_type": "int32",
            "device_class": "power",
            "enabled_by_default": True,
            "key": "ac_power",
            "name": "AC Power",
            "precision": 0,
            "register": 37004,
            "scale": 1,
            "scan_interval": "high",
            "state_class": "measurement",
            "unit": "W",
        },
    {
            "data_type": "uint16",
            "device_class": "battery",
            "enabled_by_default": True,
            "key": "battery_soc",
            "name": "Battery SOC",
            "precision": 1,
            "register": 37005,
            "scale": 1,
            "scan_interval": "medium",
            "state_class": "measurement",
            "unit": "%",
        },
]

# BINARY_SENSOR_DEFINITIONS
BINARY_SENSOR_DEFINITIONS = [
    {
            "category": "diagnostic",
            "data_type": "uint16",
            "device_class": "connectivity",
            "enabled_by_default": False,
            "icon": "mdi:check-network-outline",
            "key": "wifi_status",
            "name": "WiFi Status",
            "register": 30300,
            "scan_interval": "medium",
            "unit": None,
        },
    {
            "category": "diagnostic",
            "data_type": "uint16",
            "device_class": "connectivity",
            "enabled_by_default": False,
            "icon": "mdi:cloud-outline",
            "key": "cloud_status",
            "name": "Cloud Status",
            "register": 30302,
            "scan_interval": "medium",
            "unit": None,
        },
]

# SELECT_DEFINITIONS
SELECT_DEFINITIONS = []

# SWITCH_DEFINITIONS
SWITCH_DEFINITIONS = []

# NUMBER_DEFINITIONS
NUMBER_DEFINITIONS = []

# BUTTON_DEFINITIONS
BUTTON_DEFINITIONS = []

# EFFICIENCY_SENSOR_DEFINITIONS
EFFICIENCY_SENSOR_DEFINITIONS = [
    {
            "dependency_keys": {
                "charge": "total_charging_energy",
                "discharge": "total_discharging_energy",
            },
            "device_class": "battery",
            "key": "round_trip_efficiency_total",
            "mode": "round_trip",
            "name": "Round-Trip Efficiency Total",
            "state_class": "measurement",
            "unit": "%",
        },
    {
            "dependency_keys": {
                "charge": "total_monthly_charging_energy",
                "discharge": "total_monthly_discharging_energy",
            },
            "device_class": "battery",
            "key": "round_trip_efficiency_monthly",
            "mode": "round_trip",
            "name": "Round-Trip Efficiency Monthly",
            "state_class": "measurement",
            "unit": "%",
        },
    {
            "dependency_keys": {
                "ac_power": "ac_power",
                "battery_power": "battery_power",
            },
            "device_class": "battery",
            "key": "conversion_efficiency",
            "mode": "conversion",
            "name": "Conversion Efficiency",
            "state_class": "measurement",
            "unit": "%",
        },
]

# STORED_ENERGY_SENSOR_DEFINITIONS
STORED_ENERGY_SENSOR_DEFINITIONS = [
    {
            "dependency_keys": {
                "capacity": "battery_total_energy",
                "soc": "battery_soc",
            },
            "device_class": "energy",
            "key": "stored_energy",
            "name": "Stored Energy",
            "state_class": "total",
            "unit": "kWh",
        },
]

# UNMATCHED_CSV_ENTRIES
# 30005 -> Offgrid Voltage
# 30006 -> AC Power - Same as 37004
# 30007 -> Offgrid Current?
# 30200 -> Don't change
# 30301 -> BT Status
# 30350 -> Communication module fireware version
# 30400 -> Always 0
# 37000 -> Always 1
# 37001 -> Always 0
# 37002 -> Always 0
# 37003 -> Always 0
# 37006 -> Cell temperature
# 37007 -> Maximum cell voltage
# 37008 -> Minimum cell voltage
# 37009 -> Always 0
# 45603 -> Dont seem to change

