"""
Register and entity definitions for Marstek Venus E versions v1 and v2.

This file contains the SENSOR_DEFINITIONS, BINARY_SENSOR_DEFINITIONS,
SELECT_DEFINITIONS, SWITCH_DEFINITIONS, NUMBER_DEFINITIONS, BUTTON_DEFINITIONS,
EFFICIENCY_SENSOR_DEFINITIONS and STORED_ENERGY_SENSOR_DEFINITIONS that were
previously in `const.py` and correspond to v1/v2 devices.

missing:
    sensor:
    - vms_version
    - cell_xx_voltage 1tm16
"""

# Definitions for sensors to be read from the Modbus device
SENSOR_DEFINITIONS = [
    {
        "register": 31000,
        "count": 10,
        "data_type": "char",
        "unit": None,
        "key": "device_name",
        "enabled_by_default": True,
        "scan_interval": "very_low",
        "precision": 0,
    },
    {
        "register": 31200,
        "count": 10,
        "data_type": "char",
        "unit": None,
        "key": "sn_code",
        "enabled_by_default": False,
        "scan_interval": "very_low",
        "precision": 0,
    },
    {
        "register": 31100,
        "scale": 0.01,
        "unit": None,
        "icon": "mdi:ticket-confirmation-outline",
        "category": "diagnostic",
        "key": "software_version",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 2,
        "scan_interval": "very_low",
    },
    {
        "register": 31102,
        "unit": None,
        "icon": "mdi:battery-check-outline",
        "category": "diagnostic",
        "key": "bms_version",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "register": 31101,
        "unit": None,
        "category": "diagnostic",
        "icon": "mdi:ticket-confirmation-outline",
        "key": "ems_version",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "register": 30800,
        "count": 6,
        "unit": None,
        "category": "diagnostic",
        "icon": "mdi:ticket-confirmation-outline",
        "key": "comm_module_firmware",
        "enabled_by_default": True,
        "data_type": "char",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "register": 30402,
        "count": 6,
        "unit": None,
        "key": "mac_address",
        "enabled_by_default": True,
        "data_type": "char",
        "precision": 0,
        "scan_interval": "very_low",
    },
    {
        "register": 32104,
        "scale": 1,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "key": "battery_soc",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32105,
        "scale": 0.001,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total",
        "key": "battery_total_energy",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 3,
        "scan_interval": "low",
    },
    {
        "register": 32100,
        "scale": 0.01,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "battery_voltage",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32101,
        "scale": 0.01,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "key": "battery_current",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32102,
        "count": 2,
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "key": "battery_power",
        "enabled_by_default": True,
        "data_type": "int32",
        "precision": 1,
        "scan_interval": "high",
    },
    {
        "register": 35000,
        "scale": 0.1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "key": "internal_temperature",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 2,
        "scan_interval": "medium",
    },
    {
        "register": 35001,
        "scale": 0.1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "key": "internal_mos1_temperature",
        "enabled_by_default": False,
        "data_type": "int16",
        "precision": 2,
        "scan_interval": "medium",
    },
    {
        "register": 35002,
        "scale": 0.1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "key": "internal_mos2_temperature",
        "enabled_by_default": False,
        "data_type": "int16",
        "precision": 2,
        "scan_interval": "medium",
    },
    {
        "register": 32200,
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "ac_voltage",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32201,
        "scale": 0.01,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "key": "ac_current",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32202,
        "count": 2,
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "key": "ac_power",
        "enabled_by_default": True,
        "data_type": "int32",
        "precision": 0,
        "scan_interval": "high",
    },
    {
        "register": 32204,
        "scale": 0.01,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "key": "ac_frequency",
        "enabled_by_default": True,
        "data_type": "int16",
        "precision": 2,
        "scan_interval": "medium",
    },
    {
        "register": 33000,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "key": "total_charging_energy",
        "enabled_by_default": True,
        "data_type": "uint32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33002,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "key": "total_discharging_energy",
        "enabled_by_default": True,
        "data_type": "int32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33004,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "key": "total_daily_charging_energy",
        "enabled_by_default": False,
        "data_type": "uint32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33006,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "key": "total_daily_discharging_energy",
        "enabled_by_default": False,
        "data_type": "int32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33008,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "key": "total_monthly_charging_energy",
        "enabled_by_default": False,
        "data_type": "uint32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 33010,
        "count": 2,
        "scale": 0.01,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "key": "total_monthly_discharging_energy",
        "enabled_by_default": False,
        "data_type": "int32",
        "precision": 2,
        "scan_interval": "low",
    },
    {
        "register": 35010,
        "scale": 1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "key": "max_cell_temperature",
        "enabled_by_default": False,
        "data_type": "int16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 35011,
        "scale": 1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "key": "min_cell_temperature",
        "enabled_by_default": False,
        "data_type": "int16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 37007,
        "scale": 0.001,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "max_cell_voltage",
        "enabled_by_default": False,
        "data_type": "int16",
        "precision": 3,
        "scan_interval": "medium",
    },
    {
        "register": 37008,
        "scale": 0.001,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "min_cell_voltage",
        "enabled_by_default": False,
        "data_type": "int16",
        "precision": 3,
        "scan_interval": "medium",
    },
    {
        "register": 35100,
        "scale": 1,
        "unit": None,
        "icon": "mdi:state-machine",
        "key": "inverter_state",
        "enabled_by_default": True,
        "data_type": "uint16",
        "precision": 0,
        "states": {
            0: "Sleep",
            1: "Standby",
            2: "Charge",
            3: "Discharge",
            4: "Backup Mode",
            5: "OTA Upgrade",
            6: "Bypass",
        },
        "scan_interval": "high",
    },
    {
        "register": 36100,
        "count": 4,
        "data_type": "uint16",
        "key": "fault_status",
        "device_class": "problem",
        "icon": "mdi:alert",
        "category": "diagnostic",
        "enabled_by_default": True,
        "scan_interval": "high",
        "bit_descriptions": {
            0: "Grid Overvoltage",
            1: "Grid Undervoltage",
            2: "Grid Overfrequency",
            3: "Grid Underfrequency",
            4: "Grid Peak Voltage",
            5: "Current Dcover",
            6: "Voltage Dcover",
            16: "BAT Overvoltage",
            17: "BAT Undervoltage",
            18: "BAT Overcurrent",
            19: "BAT low SOC",
            20: "BAT communication failure",
            21: "BMS protect",
            32: "Inverter soft start timeout",
            33: "self-checking failure",
            34: "eeprom failure",
            35: "other system failure",
            48: "Hardware Bus overvoltage",
            49: "Hardware Output overcurrent",
            50: "Hardware trans overcurrent",
            51: "Hardware battery overcurrent",
            52: "Hardware Protecion",
            53: "Output Overcurrent",
            54: "High Voltage bus overvoltage",
            55: "High Voltage bus undervoltage",
            56: "Overpower Protection",
            57: "FSM abnormal",
            58: "Overtemperature Protection",
        },
    },
    {
        "register": 36000,
        "count": 2,
        "data_type": "uint16",
        "key": "alarm_status",
        "device_class": "problem",
        "icon": "mdi:alert",
        "enabled_by_default": True,
        "category": "diagnostic",
        "unit": None,
        "precision": 0,
        "scan_interval": "high",
        "bit_descriptions": {
            0: "PLL Abnormal Restart",
            1: "Overtemperature Limit",
            2: "Low Temperature Limit",
            3: "Fan Abnormal Warning",
            4: "Low Battery SOC Warning",
            5: "Output Overcurrent Warning",
            6: "Abnormal Line Sequence Detection",
            16: "WiFi Abnormal",
            17: "BLE Abnormal",
            18: "Network Abnormal",
            19: "CT Connection Abnormal",
        },
    },
    {
        "register": 41100,
        "data_type": "uint16",
        "unit": None,
        "icon": "mdi:home-automation",
        "key": "modbus_address",
        "enabled_by_default": False,
        "scan_interval": "very_low",
        "precision": 0,
    },
    {
        "register": 32300,
        "scale": 0.1,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "key": "ac_offgrid_voltage",
        "enabled_by_default": False,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32301,
        "scale": 0.01,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "key": "ac_offgrid_current",
        "enabled_by_default": False,
        "data_type": "uint16",
        "precision": 1,
        "scan_interval": "medium",
    },
    {
        "register": 32302,
        "count": 2,
        "scale": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "key": "ac_offgrid_power",
        "enabled_by_default": False,
        "data_type": "int32",
        "precision": 0,
        "scan_interval": "high",
    },
    {
        "register": 30303,
        "scale": -1,
        "data_type": "uint16",
        "device_class": "diagnostic",
        "unit": "dBm",
        "icon": "mdi:wifi",
        "category": "diagnostic",
        "key": "wifi_signal_strength",
        "enabled_by_default": False,
        "precision": 0,
        "scan_interval": "high",
    },
]

# Binary sensors
BINARY_SENSOR_DEFINITIONS = [
    {
        "register": 30300,
        "data_type": "uint16",
        "unit": None,
        "category": "diagnostic",
        "device_class": "connectivity",
        "icon": "mdi:check-network-outline",
        "key": "wifi_status",
        "enabled_by_default": False,
        "scan_interval": "medium",
    },
    {
        "register": 30302,
        "data_type": "uint16",
        "unit": None,
        "category": "diagnostic",
        "device_class": "connectivity",
        "icon": "mdi:cloud-outline",
        "key": "cloud_status",
        "enabled_by_default": False,
        "scan_interval": "medium",
    },
    {
        "register": 41010,
        "data_type": "uint16",
        "unit": None,
        "icon": "mdi:battery-arrow-down-outline",
        "key": "discharge_limit_mode",
        "enabled_by_default": False,
        "scan_interval": "medium",
    },
]

# Selects
SELECT_DEFINITIONS = [
    {
        "register": 43000,
        "key": "user_work_mode",
        "enabled_by_default": True,
        "scan_interval": "high",
        "options": {"manual": 0, "anti_feed": 1, "trade_mode": 2},
    },
    {
        "register": 42010,
        "key": "force_mode",
        "enabled_by_default": False,
        "scan_interval": "high",
        "options": {"stop": 0, "charge": 1, "discharge": 2},
    },
    {
        "register": 44100,
        "key": "grid_standard",
        "enabled_by_default": True,
        "scan_interval": "high",
        "options": {
            "Auto": 0,
            "EN50549": 1,
            "Netherlands": 2,
            "Germany": 3,
            "Austria": 4,
            "United Kingdom": 5,
            "Spain": 6,
            "Poland": 7,
            "Italy": 8,
            "China": 9,
        },
    },
]

# Switches
SWITCH_DEFINITIONS = [
    {
        "register": 41200,
        "command_on": 0,
        "command_off": 1,
        "key": "backup_function",
        "enabled_by_default": True,
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 42000,
        "command_on": 21930,
        "command_off": 21947,
        "key": "rs485_control_mode",
        "enabled_by_default": False,
        "data_type": "uint16",
        "scan_interval": "high",
    },
]

# Numbers
NUMBER_DEFINITIONS = [
    {
        "register": 42020,
        "key": "set_charge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-up-outline",
        "min": 0,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 42021,
        "key": "set_discharge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-down-outline",
        "min": 0,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 44002,
        "key": "max_charge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-up-outline",
        "min": 0,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 44003,
        "key": "max_discharge_power",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-down-outline",
        "min": 0,
        "max": 2500,
        "step": 50,
        "unit": "W",
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 44000,
        "key": "charging_cutoff_capacity",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-up-outline",
        "min": 80,
        "max": 100,
        "step": 1,
        "unit": "%",
        "scale": 0.1,
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 44001,
        "key": "discharging_cutoff_capacity",
        "enabled_by_default": False,
        "icon": "mdi:battery-arrow-down-outline",
        "min": 12,
        "max": 30,
        "step": 1,
        "unit": "%",
        "scale": 0.1,
        "data_type": "uint16",
        "scan_interval": "high",
    },
    {
        "register": 42011,
        "key": "charge_to_soc",
        "enabled_by_default": False,
        "icon": "mdi:battery-sync-outline",
        "min": 10,
        "max": 100,
        "step": 1,
        "unit": "%",
        "scale": 1,
        "data_type": "uint16",
        "scan_interval": "high",
    },
]

# Buttons
BUTTON_DEFINITIONS = [
    {
        "register": 41000,
        "command": 21930,
        "icon": "mdi:restart",
        "category": "diagnostic",
        "key": "reset_device",
        "enabled_by_default": False,
        "data_type": "uint16",
    },
    {
        "register": 41001,
        "command": 21930,
        "icon": "mdi:factory",
        "category": "diagnostic",
        "key": "factory_reset",
        "enabled_by_default": False,
        "data_type": "uint16",
    },
]

# Efficiency sensors
EFFICIENCY_SENSOR_DEFINITIONS = [
    {
        "key": "round_trip_efficiency_total",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "mode": "round_trip",
        "dependency_keys": {
            "charge": "total_charging_energy",
            "discharge": "total_discharging_energy",
        },
    },
    {
        "key": "round_trip_efficiency_monthly",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "mode": "round_trip",
        "dependency_keys": {
            "charge": "total_monthly_charging_energy",
            "discharge": "total_monthly_discharging_energy",
        },
    },
    {
        "key": "conversion_efficiency",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "mode": "conversion",
        "dependency_keys": {"battery_power": "battery_power", "ac_power": "ac_power"},
    },
]

# Stored energy sensors
STORED_ENERGY_SENSOR_DEFINITIONS = [
    {
        "key": "stored_energy",
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total",
        "dependency_keys": {"soc": "battery_soc", "capacity": "battery_total_energy"},
    },
]
